DROP TABLE IF EXISTS visitor;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS searching_visitor;

CREATE TABLE room (
	id VARCHAR PRIMARY KEY,
	room_name VARCHAR NOT NULL,
	room_size INTEGER NOT NULL,
	room_type BOOLEAN NOT NULL,
	free_place INTEGER NOT NULL,
	playing BOOLEAN NOT NULL
);
